import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

describe('README usage guide', () => {
  it('keeps the root entrypoint scannable and delegates detailed work to generated README', async () => {
    const readme = await readFile(path.join(repoRoot, 'README.md'), 'utf8');

    expect(readme).toContain('OpenAPI에서 API 흐름을 **Scenario YAML**로 만들고');
    expect(readme).toContain('`openapi-k6`의 중심은 k6 파일 생성보다 scenario 작성과 검증입니다.');
    expect(readme).toContain('로그인 -> 토큰 추출 -> 인증 API 호출 같은 흐름을 YAML로 연결하고');

    expect(readme).toContain('## 한눈에 보기');
    expect(readme).toContain('init -> sync -> catalog 검색 -> scenario YAML 작성 -> validate -> test -> run');
    expect(readme).toContain('| 1 | `npx --yes openapi-k6 init` | 백엔드 프로젝트에 `load-tests/` 생성 |');
    expect(readme).toContain('| 3 | `npx --yes openapi-k6 catalog --query login` | scenario에 쓸 endpoint 후보 검색 |');
    expect(readme).toContain('| 4 | `load-tests/scenarios/*.yaml` 작성 | catalog 기준으로 API 흐름 작성 |');
    expect(readme).toContain('| 5 | `npx --yes openapi-k6 validate -s smoke` | OpenAPI snapshot 기준 정적 검증 |');
    expect(readme).toContain('| 6 | `npx --yes openapi-k6 test -s smoke` | Node.js에서 scenario 1회 실행 검증 |');
    expect(readme).toContain('| 7 | `npx --yes openapi-k6 run -s smoke --log -- --vus 1` | 정적 검증, k6 스크립트 생성, k6 실행 |');
    expect(readme).toContain('| 8 | `npx --yes openapi-k6 generate -s smoke`, `./load-tests/run.sh smoke --log` | 스크립트만 생성하거나 runner로 실행 |');
    expect(readme).toContain('k6 실행 전에는 `validate`와 `test`를 먼저 통과시키는 흐름을 권장합니다.');
    expect(readme).toContain('- `validate`: API 호출 없이 OpenAPI snapshot 기준으로 operation, path/query/header/body, context template, condition/extract 문법을 확인합니다.');
    expect(readme).toContain('- `test`: 실제 API에 1회 요청해 URL, header, query, path, body, 환경변수, condition, extract 동작을 확인합니다.');

    expect(readme).toContain('## 핵심 기능');
    expect(readme).toContain('| Scenario YAML | 로그인, 추출, 인증 요청 같은 API 흐름을 YAML로 표현합니다. |');
    expect(readme).toContain('| Scenario vars/fixtures | `vars:`와 fixture 파일로 SKU, tenant, 테스트 데이터 같은 반복 값을 관리하고 `{{vars.sku}}`로 참조합니다. |');
    expect(readme).toContain('| 재사용 step include | 로그인/seed 같은 공통 step YAML을 여러 scenario에서 include해 반복을 줄입니다. |');
    expect(readme).toContain('| 검증 관문 | k6 실행 전에 OpenAPI 정합성, 요청 구성, 추출, 설정 오류를 잡습니다. |');
    expect(readme).toContain('| 로컬 UI | 작성한 scenario 목록을 보고 서버 상태 확인, validate/test 실행, CLI 로그 확인을 브라우저에서 합니다. |');
    expect(readme).toContain('| OpenAPI catalog | `catalog` 명령으로 scenario에 쓸 `operationId`, `method`, `path`를 찾습니다. |');
    expect(readme).toContain('| 멀티모듈/멀티서버 | `module add`와 `api.module`로 서로 다른 OpenAPI/Swagger 서버를 하나의 scenario에서 연결합니다. |');
    expect(readme).toContain('| Doctor 점검 | `doctor`로 config, snapshot, catalog, scaffold metadata, module env 충돌, k6 설치 여부를 확인합니다. |');
    expect(readme).toContain('| `load-tests/` 작업 공간 | config, scenario, snapshot, 생성된 k6 스크립트, runner를 백엔드 프로젝트 안에서 관리합니다. |');
    expect(readme).toContain('| AI 작업 프롬프트 | 루트 README에서 시작하고 생성 README로 이어지는 작업 지침을 제공합니다. |');

    expect(readme).toContain('<summary>작동 예시와 test 출력</summary>');
    expect(readme).toContain('`login` 응답에서 `token`을 추출해 다음 API의 `Authorization` header에 넣는 흐름입니다.');
    expect(readme).toContain('name: login-and-read-profile');
    expect(readme).toContain('operationId: loginUser');
    expect(readme).toContain('Authorization: "Bearer {{token}}"');
    expect(readme).toContain('`openapi-k6 test`는 이 YAML을 먼저 실행하고, 실패한 step과 검증식을 출력합니다.');
    expect(readme).toContain('$ npx --yes openapi-k6 test -s login-and-read-profile');
    expect(readme).toContain('scenario: login-and-read-profile');
    expect(readme).toContain('[1/2] login');
    expect(readme).toContain('extract: ✓ token');
    expect(readme).toContain('[2/2] get-me');
    expect(readme).toContain('summary: ✓ PASS');
    expect(readme).toContain('`test`가 통과한 scenario만 `openapi-k6 run`으로 k6까지 실행하거나 `openapi-k6 generate`로 스크립트를 생성합니다.');

    expect(readme).toContain('## 지원 범위');
    expect(readme).toContain('Node.js 20 이상');
    expect(readme).toContain('OpenAPI 3.x 문서');
    expect(readme).toContain('검증과 실행 시 접근 가능한 백엔드 서버');
    expect(readme).toContain('k6 스크립트 실행용 k6 별도 설치');
    expect(readme).toContain('Swagger/OpenAPI 2.0 문서는 지원하지 않습니다.');
    expect(readme).toContain('목표는 범용 API 테스트 플랫폼이 아니라 OpenAPI 기반 scenario 검증과 k6 스크립트 생성입니다.');

    expect(readme).toContain('## 진행 방식 선택');
    expect(readme).toContain('먼저 진행 방식을 고릅니다.');
    expect(readme).toContain('| AI에게 맡기기 | 아래 [AI에게 맡기기](#ai에게-맡기기) 프롬프트를 복사해서 agent에 전달합니다. |');
    expect(readme).toContain('| 직접 실행하기 | [직접 실행 단계](#직접-실행-단계)의 1번부터 순서대로 실행합니다. |');
    expect(readme).toContain('## 직접 실행 단계');
    expect(readme).toContain('### 1. 작업 공간 생성');
    expect(readme).toContain('npx --yes openapi-k6 init');
    expect(readme).toContain('백엔드 프로젝트 루트에서 실행합니다.');
    expect(readme).toContain('API base URL [http://localhost:8080]: https://api.example.com');
    expect(readme).toContain('`API base URL`에는 Swagger UI 주소가 아니라 실제 API 요청의 기본 주소를 입력합니다.');
    expect(readme).toContain('OpenAPI spec URL/file path or "skip" [https://api.example.com/v3/api-docs]:');
    expect(readme).toContain('이때는 OpenAPI JSON/YAML URL이나 파일 경로를 입력합니다.');
    expect(readme).toContain('### 2. 설정 확인');
    expect(readme).toContain('`load-tests/config.yaml`에 TODO가 남아 있으면 실제 API 정보로 채웁니다.');
    expect(readme).toContain('baseUrl: https://api.example.com');
    expect(readme).toContain('openapi: https://api.example.com/v3/api-docs');
    expect(readme).toContain('`baseUrl`은 실제 API 요청의 기본 주소이고, `openapi`는 `sync`가 읽을 OpenAPI 문서 URL 또는 파일 경로입니다.');
    expect(readme).toContain('### 3. OpenAPI snapshot/catalog 생성');
    expect(readme).toContain('npx --yes openapi-k6 sync');
    expect(readme).toContain('### 4. Scenario 작성');
    expect(readme).toContain('이 단계의 목표는 catalog에서 API를 고르고, 그 값을 scenario YAML에 옮기는 것입니다.');
    expect(readme).toContain('step 하나가 API 요청 하나입니다.');
    expect(readme).toContain('#### 4-1. Endpoint 찾기');
    expect(readme).toContain('npx --yes openapi-k6 catalog --query login');
    expect(readme).toContain('출력에서 우선 볼 값은 `operationId`, `body`, `parameters`입니다.');
    expect(readme).toContain('<summary>catalog 검색과 출력 읽는 법</summary>');
    expect(readme).toContain('`--query`는 검색어로 찾기, `--tag`는 OpenAPI tag로 좁히기입니다.');
    expect(readme).toContain('`--query login`: catalog 전체에서 `login`이라는 글자가 들어간 API를 찾습니다.');
    expect(readme).toContain('`--tag auth`: OpenAPI에서 `auth` tag로 묶인 API만 봅니다.');
    expect(readme).toContain('처음에는 `--query`로 찾고, 결과가 많으면 `--tag`나 `--method POST`로 좁히면 됩니다.');
    expect(readme).toContain('`login`, `auth`는 원하는 API 이름이나 tag로 바꿔 실행합니다.');
    expect(readme).toContain('Catalog: load-tests/openapi/app.catalog.json');
    expect(readme).toContain('Query: login');
    expect(readme).toContain('POST   /auth/login');
    expect(readme).toContain('operationId: loginUser');
    expect(readme).toContain('body: yes (application/json)');
    expect(readme).toContain('`operationId`: scenario의 `api.operationId`에 넣습니다.');
    expect(readme).toContain('`body: yes`: `request.body` 또는 `request.multipart`가 필요한 API입니다.');
    expect(readme).toContain('`parameters`: 나오면 `request.pathParams`, `request.query`, `request.headers` 중 맞는 위치에 값을 넣습니다.');
    expect(readme).toContain('`method`와 `path`: `operationId`가 없거나 애매할 때 `api.method`, `api.path`로 쓸 수 있습니다.');
    expect(readme).toContain('`operationId`는 openapi-k6가 새로 만드는 이름이 아닙니다.');
    expect(readme).toContain('백엔드 OpenAPI 문서에 있는 `operationId`를 `sync`가 `load-tests/openapi/*.catalog.json`에 복사합니다.');
    expect(readme).toContain('OpenAPI에 `operationId`가 없으면 catalog에도 안 나오므로 `api.method`와 `api.path`를 씁니다.');
    expect(readme).toContain('같은 module 안에서 `operationId`가 중복되면 `validate`, `generate`, `test`, `run`이 실패합니다.');
    expect(readme).toContain('서로 다른 module의 같은 `operationId`는 `api.module`로 구분해서 사용할 수 있습니다.');
    expect(readme).toContain('#### 4-2. Scenario 파일 선택');
    expect(readme).toContain('`load-tests/scenarios/smoke.yaml`은 `init`이 만든 기본 예시 scenario입니다.');
    expect(readme).toContain('처음 동작 확인은 `smoke.yaml`을 수정해도 되고, 실제 업무 흐름은 `load-tests/scenarios/order-flow.yaml`처럼 새 파일로 만들어도 됩니다.');
    expect(readme).toContain('#### 4-3. 최소 YAML 작성');
    expect(readme).toContain('처음에는 아래 필드만 채우면 됩니다.');
    expect(readme).toContain('- `api.operationId`: catalog에서 고른 `operationId`');
    expect(readme).toContain('operationId: loginUser # catalog에서 고른 operationId');
    expect(readme).toContain('from: $.token # 응답 JSON에서 token을 저장');
    expect(readme).toContain('Authorization: "Bearer {{token}}" # 앞 step에서 추출한 token 사용');
    expect(readme).toContain('#### 4-4. 선택: 데이터와 공통 step');
    expect(readme).toContain('처음 scenario는 이 섹션을 건너뛰어도 됩니다.');
    expect(readme).toContain('| 같은 값을 여러 step에서 재사용 | `vars:` | `{{vars.sku}}` |');
    expect(readme).toContain('| stage/prod 값을 분리 | `fixtures:` 또는 `--var-file` | `fixtures/stage.yaml` |');
    expect(readme).toContain('| 로그인/seed step 재사용 | `include` | `- include: ./partials/login.yaml` |');
    expect(readme).toContain('fixture와 include 경로는 실행하는 scenario 파일 기준 상대 경로이며, 그 scenario 디렉터리 밖으로 나갈 수 없습니다.');
    expect(readme).toContain('<summary>예시와 우선순위</summary>');
    expect(readme).toContain('# load-tests/scenarios/order-flow.yaml');
    expect(readme).toContain('- ./fixtures/dev.yaml');
    expect(readme).toContain('- include: ./partials/login.yaml');
    expect(readme).toContain('sku: "{{vars.sku}}"');
    expect(readme).toContain('partial 파일은 `steps`만 두면 됩니다. 포함된 step의 `extract` 값은 뒤 step에서 그대로 참조할 수 있습니다.');
    expect(readme).toContain('include 파일에는 `vars:`나 `fixtures:`를 두지 않고, 변수는 실행하는 scenario 파일에서 관리합니다.');
    expect(readme).toContain('값 우선순위는 scenario `fixtures:` < scenario `vars:` < CLI `--var-file` < CLI `--var`입니다.');
    expect(readme).toContain('npx --yes openapi-k6 validate -s smoke --var-file load-tests/scenarios/fixtures/stage.yaml');
    expect(readme).toContain('npx --yes openapi-k6 test -s smoke --var sku=ABC-001');
    expect(readme).toContain('### 5. Scenario 정적 검증');
    expect(readme).toContain('npx --yes openapi-k6 validate -s smoke');
    expect(readme).toContain('`validate`는 백엔드에 요청하지 않고 scenario YAML을 OpenAPI snapshot과 대조합니다.');
    expect(readme).toContain('필수 request 값, context template, `condition`, `extract.from` 문법을 확인합니다.');
    expect(readme).toContain('### 6. Scenario 실행 검증');
    expect(readme).toContain('npx --yes openapi-k6 test -s smoke');
    expect(readme).toContain('`test`는 실제 백엔드에 1회 요청해 URL, status, `condition`, `extract`를 확인합니다.');
    expect(readme).toContain('scenario: smoke');
    expect(readme).toContain('[1/2] login');
    expect(readme).toContain('request: POST /auth/login');
    expect(readme).toContain('extract: ✓ token');
    expect(readme).toContain('summary: ✓ PASS');
    expect(readme).toContain('여기서 `url`, `status`, `checks`, `extract`, 마지막 `summary`를 확인합니다.');
    expect(readme).toContain('실패하면 해당 step 아래에 error와 response body 일부가 표시되고, 비밀 값은 마스킹됩니다.');
    expect(readme).toContain('시나리오 이름을 매번 입력하기 번거로우면 로컬 UI를 켭니다.');
    expect(readme).toContain('npx --yes openapi-k6 ui');
    expect(readme).toContain('UI에서는 scenario 목록을 클릭해 step/module/env 참조를 보고, 서버와 snapshot 상태를 확인한 뒤 `Validate` 또는 `Test` 버튼으로 같은 CLI 검증을 실행할 수 있습니다.');
    expect(readme).toContain('오른쪽 출력 영역에는 터미널에서 보던 CLI 로그가 그대로 표시됩니다.');
    expect(readme).toContain('### 7. k6 실행');
    expect(readme).toContain('npx --yes openapi-k6 run -s smoke --log -- --vus 1 --iterations 1');
    expect(readme).toContain('`run`은 scenario를 정적 검증하고, k6 스크립트를 다시 생성한 뒤 `k6 run`을 실행합니다.');
    expect(readme).toContain('k6 옵션은 `--` 뒤에 붙입니다.');
    expect(readme).toContain('npx --yes openapi-k6 generate -s smoke');
    expect(readme).toContain('./load-tests/run.sh smoke --log');
    expect(readme).toContain('k6 스크립트 실행에는 k6 설치가 필요합니다.');
    expect(readme).toContain('## 여러 백엔드 서버 연결');
    expect(readme).toContain('`init` 직후 config는 단일 서버용 `default` module만 들어 있습니다.');
    expect(readme).toContain('그 서버가 업무 서버라면 그대로 두고, 추가로 필요한 서버만 module로 등록합니다.');
    expect(readme).toContain('npx --yes openapi-k6 module add auth --base-url https://auth-api.example.com --sync');
    expect(readme).not.toContain('npx --yes openapi-k6 module add bos --base-url https://bos-api.example.com --sync');
    expect(readme).toContain('`--sync`를 붙이면 module 설정 저장과 동시에 해당 서버의 snapshot/catalog를 만듭니다.');
    expect(readme).toContain('--openapi https://auth-api.example.com/v3/api-docs');
    expect(readme).toContain('추가 후 config는 이런 모양이 됩니다.');
    expect(readme).toContain('baseUrl: https://auth-api.example.com');
    expect(readme).toContain('root `baseUrl`과 `defaultModule`은 `api.module`이 없는 step의 fallback으로 두면 됩니다.');
    expect(readme).toContain('operationId: createOrder # api.module이 없으면 default module 사용');
    expect(readme).toContain('생성된 k6 스크립트는 `BASE_URL_AUTH`, `BASE_URL_DEFAULT` 같은 module별 환경변수를 먼저 읽습니다.');
    expect(readme).toContain('없으면 기존 `BASE_URL`과 config 기본값을 순서대로 사용합니다.');
    expect(readme).toContain('같은 `operationId`가 여러 module에 있어도 step의 `api.module` 안에서만 찾습니다.');
    expect(readme).not.toContain('cd /path/to/backend-project');

    expect(readme).not.toContain('<summary>Scenario YAML 예시</summary>');

    expect(readme).toContain('## 상세 참고');
    expect(readme).toContain('<summary>수정할 파일과 생성물</summary>');
    expect(readme).toContain('보통 직접 수정하는 파일은 `load-tests/config.yaml`, `load-tests/.env`, `load-tests/scenarios/*.yaml`입니다.');
    expect(readme).toContain('OpenAPI snapshot과 생성된 k6 스크립트는 명령으로 다시 만듭니다.');
    expect(readme).toContain('load-tests/run.sh');
    expect(readme).toContain('| `load-tests/scenarios/smoke.yaml` | 기본 예시 scenario YAML |');
    expect(readme).toContain('load-tests/scenarios/partials/login.yaml.example');
    expect(readme).toContain('load-tests/scenarios/fixtures/dev.yaml.example');
    expect(readme).toContain('기본 `load-tests/.gitignore`는 `scenarios/**`만 git 추적 대상에 남기고 scaffold/config/생성물은 제외합니다.');
    expect(readme).toContain('기존 `load-tests/config.yaml`과 scenario를 보존한 채 README, runner, `.env.example`, `.gitignore`, `.openapi-k6.json` 같은 scaffold 파일만 최신화하려면 `update`를 사용합니다.');
    expect(readme).toContain('`update`는 `load-tests/config.yaml`, `.env`, `scenarios/`, `openapi/`, `generated/`, `logs/`를 보존합니다.');
    expect(readme).toContain('오래된 scaffold에서 `validate`, `test`, `generate`, `run`을 실행하면 최신 README/runner를 받을 수 있도록 `Scaffold update available` notice와 `npx --yes openapi-k6 update` 명령이 표시됩니다.');

    expect(readme).toContain('<summary>검증 규칙과 제약</summary>');
    expect(readme).toContain('OpenAPI 3.x 문서를 대상으로 합니다. Swagger/OpenAPI 2.0 문서는 지원하지 않습니다.');
    expect(readme).toContain('`condition`은 분기가 아니라 검증식입니다.');
    expect(readme).toContain('비밀값은 scenario YAML에 직접 쓰지 않고 `{{env.NAME}}`으로 참조합니다.');
    expect(readme).toContain('`vars:`는 entry scenario에 정의하는 literal 테스트 데이터입니다.');
    expect(readme).toContain('`fixtures:`는 entry scenario 디렉터리 안의 YAML object를 읽어 `vars`로 병합합니다.');
    expect(readme).toContain('CLI `--var-file`과 `--var`는 `validate`, `generate`, `test`, `run` 실행 시점에 같은 `vars`를 덮어씁니다.');
    expect(readme).toContain('`steps` 안에서 `- include: ./partials/login.yaml`로 공통 step 파일을 펼칠 수 있습니다.');
    expect(readme).toContain('`validate`는 지원하지 않는 `condition` 표현식, `extract.from` JSONPath, 아직 이전 step에서 추출되지 않은 `{{token}}` 같은 context template 참조를 API 호출 전에 실패로 처리합니다.');
    expect(readme).toContain('`body`와 `multipart`는 같은 step에서 함께 쓰지 않습니다.');

    expect(readme).toContain('## 명령 모음');
    expect(readme).toContain('| 작업 공간 생성 | `npx --yes openapi-k6 init` |');
    expect(readme).toContain('| OpenAPI snapshot/catalog 갱신 | `npx --yes openapi-k6 sync` |');
    expect(readme).toContain('| scenario용 endpoint 검색 | `npx --yes openapi-k6 catalog --query login` |');
    expect(readme).toContain('| 로컬 UI로 scenario 선택/검증 | `npx --yes openapi-k6 ui` |');
    expect(readme).toContain('| scenario 정적 검증 | `npx --yes openapi-k6 validate -s <name>` |');
    expect(readme).toContain('| scenario 실행 검증 | `npx --yes openapi-k6 test -s <name>` |');
    expect(readme).toContain('| 환경별 vars override | `npx --yes openapi-k6 test -s <name> --var-file <fixture.yaml> --var sku=ABC-001` |');
    expect(readme).toContain('| 정적 검증, 생성, k6 실행 | `npx --yes openapi-k6 run -s <name> --log -- --vus 1` |');
    expect(readme).toContain('| k6 스크립트 생성 | `npx --yes openapi-k6 generate -s <name>` |');
    expect(readme).toContain('| k6 설치 후 실행 | `./load-tests/run.sh <name> --log` |');
    expect(readme).toContain('| 작업 공간 점검 | `npx --yes openapi-k6 doctor` |');
    expect(readme).toContain('| 기존 scaffold 안전 갱신 | `npx --yes openapi-k6 update` |');
    expect(readme).toContain('| scaffold 파일 재생성 | `npx --yes openapi-k6 init --force` |');

    expect(readme).toContain('## AI에게 맡기기');
    expect(readme).not.toContain('<summary>AI에게 맡기기</summary>');
    expect(readme).toContain('AI coding agent에게 처음 작업을 맡길 때 아래 프롬프트를 붙여넣으세요.');
    expect(readme).toContain('이 백엔드 프로젝트에 openapi-k6 Scenario YAML 검증과 k6 부하 테스트 준비를 적용해줘.');
    expect(readme).toContain('아직 load-tests/README.md가 없으면 npx --yes openapi-k6 init을 실행해.');
    expect(readme).toContain('baseUrl 또는 OpenAPI spec URL을 확실히 모르면 나에게 물어봐.');
    expect(readme).toContain('init 후 생성된 load-tests/README.md를 읽고, 그 문서의 작업 순서와 규칙을 기준으로 진행해.');
    expect(readme).toContain('npx --yes openapi-k6 sync를 실행해서 OpenAPI snapshot과 catalog를 생성해.');
    expect(readme).toContain('npx --yes openapi-k6 catalog --query login처럼 적절한 검색어로 테스트할 endpoint 후보를 확인해.');
    expect(readme).toContain('처음에는 id, api.operationId, request, extract, condition만 채워.');
    expect(readme).toContain('같은 값이나 같은 step이 반복될 때만 vars, fixtures, include를 사용해.');
    expect(readme).toContain('include 파일에는 vars:나 fixtures:를 두지 말고, 변수는 실행하는 scenario 파일에서 관리해.');
    expect(readme).toContain('npx --yes openapi-k6 validate -s <name>으로 YAML/OpenAPI 정합성을 먼저 확인해.');
    expect(readme).toContain('npx --yes openapi-k6 test -s <name>으로 실제 API 흐름을 검증해.');
    expect(readme).toContain('scenario test가 통과하기 전에는 k6 스크립트를 생성하거나 실행하지 마.');
    expect(readme).toContain('통과한 scenario만 npx --yes openapi-k6 run -s <name> --log -- --vus 1 --iterations 1로 짧게 실행해.');
    expect(readme).toContain('스크립트만 필요하면 npx --yes openapi-k6 generate -s <name>으로 생성해.');
    expect(readme).toContain('load-tests/README.md, load-tests/run.sh, load-tests/.env.example, load-tests/.gitignore, load-tests/.openapi-k6.json은 scaffold 파일이므로 명시 요청 없이는 수정하지 마.');
    expect(readme).toContain('비밀값은 scenario YAML에 직접 쓰지 말고 {{env.NAME}}으로 참조해. 실제 값은 load-tests/.env에만 둬.');
    expect(readme).toContain('작업 중간부터는 생성 README를 기준으로 따르세요.');

    expect(readme).toContain('<summary>버전 고정</summary>');
    expect(readme).toContain('pnpm add -D openapi-k6');
    expect(readme).toContain('새 배포본을 명시하려면 `npx --yes openapi-k6@latest <command>`를 사용할 수 있습니다.');
    expect(readme).toContain('팀/CI에서는 `openapi-k6@<version>`처럼 버전을 고정하는 편이 재현성에 유리합니다.');
    expect(readme).toContain('[도구 개발/유지보수](https://github.com/aqwsde321/openapi-k6-runner/blob/main/docs/03-maintainer-notes.md)');

    expect(readme).toContain('## 참고문서');
    expect(readme).toContain('[변경 이력](https://github.com/aqwsde321/openapi-k6-runner/blob/main/CHANGELOG.md)');
    expect(readme).toContain('[문서 색인](https://github.com/aqwsde321/openapi-k6-runner/blob/main/docs/README.md)');
    expect(readme).not.toContain('https://github.com/aqwsde321/openapi-k6-runner/blob/main/docs/spec/mvp-design.md');
    expect(readme).not.toContain('## 라이선스');
    expect(readme).not.toContain('현재 공개 재사용 라이선스가 지정되어 있지 않습니다.');

    expect(readme.indexOf('## 핵심 기능')).toBeLessThan(readme.indexOf('## 진행 방식 선택'));
    expect(readme.indexOf('## 지원 범위')).toBeLessThan(readme.indexOf('## 진행 방식 선택'));
    expect(readme.indexOf('## 진행 방식 선택')).toBeLessThan(readme.indexOf('## 직접 실행 단계'));
    expect(readme.indexOf('## 직접 실행 단계')).toBeLessThan(readme.indexOf('## 상세 참고'));
    expect(readme.indexOf('## 상세 참고')).toBeLessThan(readme.indexOf('<summary>작동 예시와 test 출력</summary>'));
    expect(readme.indexOf('<summary>작동 예시와 test 출력</summary>')).toBeLessThan(readme.indexOf('<summary>수정할 파일과 생성물</summary>'));
    expect(readme.indexOf('## 명령 모음')).toBeLessThan(readme.indexOf('## AI에게 맡기기'));
    expect(readme.indexOf('## AI에게 맡기기')).toBeLessThan(readme.indexOf('## 참고문서'));
  });
});
