import fs from 'node:fs/promises';
import path from 'node:path';

import type { LoadTestConfig } from '../config/load-test.config.js';
import {
  CURRENT_SCAFFOLD_VERSION,
  SCAFFOLD_METADATA_FILENAME,
} from '../scaffold/load-test.init.js';
import { formatDisplayPath, shellQuote } from './display.js';
import {
  DEFAULT_LOAD_TEST_DIR,
  resolveLoadTestDir,
} from './workspace-paths.js';

const DEFAULT_CONFIG_PATH = `${DEFAULT_LOAD_TEST_DIR}/config.yaml`;

export async function readScaffoldWarnings(
  cwd: string,
  config: LoadTestConfig | undefined,
): Promise<string[]> {
  if (config === undefined) {
    return [];
  }

  const metadataPath = path.join(resolveLoadTestDir(cwd, config), SCAFFOLD_METADATA_FILENAME);

  try {
    const raw = await fs.readFile(metadataPath, 'utf8');
    const metadata = JSON.parse(raw) as { scaffoldVersion?: unknown };
    const scaffoldVersion = typeof metadata.scaffoldVersion === 'string'
      ? metadata.scaffoldVersion
      : undefined;

    if (scaffoldVersion === undefined) {
      return [
        `${formatDisplayPath(cwd, metadataPath)} does not contain scaffoldVersion.`,
      ];
    }

    if (compareSemver(scaffoldVersion, CURRENT_SCAFFOLD_VERSION) < 0) {
      return [
        `${formatDisplayPath(cwd, resolveLoadTestDir(cwd, config))} workspace was generated by openapi-k6 ${scaffoldVersion}. Current CLI is ${CURRENT_SCAFFOLD_VERSION}.`,
      ];
    }

    return [];
  } catch (error) {
    if (
      error &&
      typeof error === 'object' &&
      'code' in error &&
      error.code === 'ENOENT'
    ) {
      return [
        `${formatDisplayPath(cwd, metadataPath)} was not found. This workspace may have been created by an older openapi-k6 scaffold.`,
      ];
    }

    if (error instanceof SyntaxError) {
      return [
        `${formatDisplayPath(cwd, metadataPath)} is not valid JSON.`,
      ];
    }

    throw error;
  }
}

export function formatScaffoldUpdateCommand(cwd: string, config: LoadTestConfig): string {
  const defaultConfigPath = path.resolve(cwd, DEFAULT_CONFIG_PATH);
  const parts = ['npx', '--yes', 'openapi-k6', 'update'];

  if (path.resolve(config.path) !== defaultConfigPath) {
    parts.push('--config', formatDisplayPath(cwd, config.path));
  }

  return parts.map(shellQuote).join(' ');
}

export function resolveScaffoldUpdateCommand(
  cwd: string,
  config: LoadTestConfig | undefined,
  warnings: string[],
): string | undefined {
  if (config === undefined || warnings.length === 0) {
    return undefined;
  }

  return formatScaffoldUpdateCommand(cwd, config);
}

function compareSemver(left: string, right: string): number {
  const leftParts = parseSemver(left);
  const rightParts = parseSemver(right);

  for (let index = 0; index < leftParts.length; index += 1) {
    const delta = leftParts[index] - rightParts[index];

    if (delta !== 0) {
      return delta;
    }
  }

  return 0;
}

function parseSemver(value: string): [number, number, number] {
  const match = /^(\d+)\.(\d+)\.(\d+)/.exec(value);

  if (match === null) {
    return [0, 0, 0];
  }

  return [
    Number(match[1]),
    Number(match[2]),
    Number(match[3]),
  ];
}
